183988 batch job scheduler
equinor/radix-job-scheduler pull request #50
Opened 2022-02-25 17:03 UTC by satr

2022-03-01 10:56 UTC, nilsgstrabo requested changes

2022-03-01 10:56 UTC, nilsgstrabo commented on api/secrets.go
> +				kube.RadixJobTypeLabel:   kube.RadixJobTypeJobSchedule,
It kube.RadixJobTypeJobSchedule correct, or should it be kube.RadixJobTypeBatchSchedule?

2022-03-01 10:59 UTC, satr commented on api/batches/batch.go
> +type Batch interface {
I was not sure about naming and imidlertid called it mode. I agree - handler technically is here. I will rename it

2022-03-01 11:00 UTC, satr commented on api/batches/batch.go
> +	batchJobs, err := model.getBatchJobs(batchName)
I'll log this error and return

2022-03-01 11:03 UTC, satr commented on api/batches/batch.go
> +	batch, err := model.common.GetJob(batchName)
I'll use job-type label for "batch-scheduler"

2022-03-01 11:03 UTC, satr commented on api/batches/batch.go
> +	if err = model.common.CreateService(batchName, jobComponent, radixDeployment); err != nil {
No, I'll delete it

2022-03-01 11:08 UTC, satr commented on api/jobs.go
> +//GetJob Gets a job ba its name
It uses receiver's properties:
```
func (model *jobModel) getAllJobs() (models.JobList, error) {
	kubeJobs, err := model.common.KubeClient.
		BatchV1().
		Jobs(model.common.Env.RadixDeploymentNamespace).
		List(
			context.TODO(),
			metav1.ListOptions{
				LabelSelector: getLabelSelectorForJobComponent(model.common.Env.RadixComponentName),
```
```
func getLabelSelectorForJobComponent(componentName string) string {
	return labels.SelectorFromSet(map[string]string{
		kube.RadixComponentLabel: componentName,
		kube.RadixJobTypeLabel:   kube.RadixJobTypeJobSchedule,
	}).String()
}
```
I'll rename the methid

2022-03-01 13:23 UTC, satr commented on api/jobs/job.go
> +type Job interface {
Renamed

2022-03-01 13:51 UTC, satr commented on api/jobs.go
> +//GetJob Gets a job ba its name
Method `GetJob` renamed to `GetBatch` (as `GetBatchJob` can be confusing with _getting a job, started by a batch_).
Also used a `getLabelSelectorForJobComponent` to limit labels.

2022-03-02 09:14 UTC, satr commented on api/batches/batch.go
> +	log.Debugf("Found %v jobs for the batche '%s' for namespace '%s'", len(batchJobs), batchName,
Fixed

2022-03-03 13:10 UTC, Pespiri approved these changes

2022-03-03 14:19 UTC, merged