Restart batch with active deployment
equinor/radix-job-scheduler pull request #86
Opened 2023-07-19 12:51 UTC by satr

2023-07-25 11:18 UTC, nilsgstrabo requested changes
As discussed, reuse secret from source RadixBatch.
Added a few minor suggestions

2023-07-26 15:13 UTC, satr commented on api/v1/batches/batch_handler.go
> +	StopBatchJob(context.Context, string, string) error
fixed

2023-07-26 15:13 UTC, satr commented on api/v1/jobs/job_handler.go
> +	StopJob(context.Context, string) error
fixed

2023-07-26 15:13 UTC, satr commented on api/v2/handler.go
> +	sourceBatchSecrets, err := h.GetSecretsForRadixBatch(sourceRadixBatch.GetName())
fixed

2023-07-27 10:24 UTC, nilsgstrabo approved these changes

2023-07-27 10:24 UTC, merged